#pragma config(Motor,  port2,           LeftDriveMotor, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           RightDriveMotor, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           LiftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           TrapDoorServo, tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           LeftGateServo, tmotorServoStandard, openLoop, reversed)
#pragma config(Motor,  port7,           RightGateServo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[LeftDriveMotor] = vexRT[Ch3];
	motor[RightDriveMotor] = vexRT[Ch2];

	while (1)
	{
		if (vexRT[Btn5D] == 1)
		{
			motor[LiftMotor] = 50;
		}
		else if (vexRT[Btn5U] == 1)
		{
			motor[LiftMotor] = -50;
		}
		else
		{
			motor[LiftMotor] = 0;
		}

		if (vexRT[Btn6D] == 1)
		{
			motor[TrapDoorServo] = 50;
		}
		else if (vexRT[Btn6U] == 1)
		{
			motor[TrapDoorServo] = -50;
		}
		else
		{
			motor[TrapDoorServo] = 0;
		}
	}
}
